package apresentacao;

import auxiliar.Perfil;
import dominio.EstadoAusencia;
import modelo.AusenciaModel;
import servico.ListaAlocacoesPendentesService;
import servico.NotificacaoService;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.UsuarioModel;
import servico.AdministrarUsuariosService;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thiago Lima
 */
public class AlocacoesPendentes extends javax.swing.JFrame {

    private JFrame previousFrame;
    
    /**
     * Creates new form AlocacoesPendentes
     */
    public AlocacoesPendentes(UsuarioModel usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Users/Thiago/Documents/NetBeansProjects/ProSub/mack_icon.jpg"));
        this.populateGrid(usuario);
    }

    public AlocacoesPendentes(JFrame previous, UsuarioModel usuario) {
        initComponents();
        previousFrame = previous;
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Users/Thiago/Documents/NetBeansProjects/ProSub/mack_icon.jpg"));
        
        //if (isPending) {
        btn_RejeitarAlocacao.setEnabled(false);
        this.populateGrid(usuario);
//            NotificacaoService listaAlocacoesPendentes = new NotificacaoService();
//            List<AusenciaModel> listaAusencias = listaAlocacoesPendentes.listarAusenciasPorEstado(EstadoAusencia.Alocacao_Pendente);
//            for (AusenciaModel model : listaAusencias) {
//                if (model.estado.equals("Alocação pendente")) {
//                    DefaultTableModel tableModel = (DefaultTableModel) tbl_Alocacoes.getModel();
//                    tableModel.addRow(new Object[]{model.codigo, model.professorAusente, model.dataInicio, model.dataFim, model.professorSubstituto, model.estado});
//                }
           // }
//        } else {
//            btn_CancelarAusencia.setEnabled(false);
//            btn_CancelarAulas.setEnabled(false);
//            NotificacaoService listaAlocacoesPendentes =  new NotificacaoService();;
//            List<AusenciaModel> listaAusencias = listaAlocacoesPendentes.listarAusencias();
//            for (AusenciaModel model : listaAusencias) {
//                if (model.estado.equals("Alocação efetuada")) {
//                    DefaultTableModel tableModel = (DefaultTableModel) tbl_Alocacoes.getModel();
//                    tableModel.addRow(new Object[]{model.codigo,
//                                                    model.professorAusente,
//                                                    model.dataInicio,
//                                                    model.dataFim,
//                                                    model.professorSubstituto,
//                                                    model.estado});
//                }
//            }
//        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_AceitarAlocacao = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Alocacoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_RejeitarAlocacao = new javax.swing.JToggleButton();
        btn_EfetuarAlocacao = new javax.swing.JToggleButton();
        btn_CancelarAusencia = new javax.swing.JToggleButton();
        btn_CancelarAulas = new javax.swing.JToggleButton();
        btn_Cancelar = new javax.swing.JToggleButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alocações Pendentes");
        setName("frm_AlocacoesPendentes"); // NOI18N
        setResizable(false);

        btn_AceitarAlocacao.setText("Aceitar Alocação");

        tbl_Alocacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Professor", "Início", "Fim", "Substituto", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Alocacoes);

        jLabel1.setText("Ações:");

        btn_RejeitarAlocacao.setLabel("Rejeitar Alocação");
        btn_RejeitarAlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RejeitarAlocacaoActionPerformed(evt);
            }
        });

        btn_EfetuarAlocacao.setLabel("Efetuar Alocação");
        btn_EfetuarAlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EfetuarAlocacaoActionPerformed(evt);
            }
        });

        btn_CancelarAusencia.setText("Cancelar Ausência");

        btn_CancelarAulas.setText("Cancelar Aulas");

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_AceitarAlocacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(btn_RejeitarAlocacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_EfetuarAlocacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CancelarAusencia, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btn_CancelarAulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AceitarAlocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_RejeitarAlocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_EfetuarAlocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_CancelarAusencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_CancelarAulas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Cancelar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        try {
            this.dispose(); 
            previousFrame.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro ao retornar para janela anterior!");
        }   
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_RejeitarAlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RejeitarAlocacaoActionPerformed
        MotivoRejeitarAlocacao motivoRejeitarAlocacao = new MotivoRejeitarAlocacao(this);
        motivoRejeitarAlocacao.setVisible(true);
    }//GEN-LAST:event_btn_RejeitarAlocacaoActionPerformed

    private void btn_EfetuarAlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EfetuarAlocacaoActionPerformed
        ListaProfessores listaProfessores = new ListaProfessores(this);
        listaProfessores.setVisible(true);
    }//GEN-LAST:event_btn_EfetuarAlocacaoActionPerformed

    
    private void populateGrid(UsuarioModel usuario){
        
            NotificacaoService listaAlocacoesPendentes = new NotificacaoService();
            List<AusenciaModel> listaAusencias = null;
                    
                    
            
            Perfil perfil = usuario.profile;
            
            if(perfil.equals(Perfil.ADMINISTRADOR)){
                listaAusencias = listaAlocacoesPendentes.listarAusencias();
            }
            else if(perfil.equals(Perfil.FUNCIONARIO)){
                listaAusencias = listaAlocacoesPendentes.listarAusencias();
            }
            else if(perfil.equals(Perfil.PROFESSOR)){
                listaAusencias = listaAlocacoesPendentes.listarAusenciasPorProfessor(usuario.Usuario);
            }
            else{
                //Algum erro
            }
        
            
            for (AusenciaModel model : listaAusencias) {
                if (model.estado.equals("Alocação pendente")) {
                    DefaultTableModel tableModel = (DefaultTableModel) tbl_Alocacoes.getModel();
                    tableModel.addRow(new Object[]{model.codigo, model.professorAusente, model.dataInicio, model.dataFim, model.professorSubstituto, model.estado});
                }
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlocacoesPendentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlocacoesPendentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlocacoesPendentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlocacoesPendentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                AdministrarUsuariosService userService = new AdministrarUsuariosService();

                UsuarioModel usuarioLogando = userService.obterUsuario("admin");
                
                new AlocacoesPendentes(usuarioLogando).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_AceitarAlocacao;
    private javax.swing.JToggleButton btn_Cancelar;
    private javax.swing.JToggleButton btn_CancelarAulas;
    private javax.swing.JToggleButton btn_CancelarAusencia;
    private javax.swing.JToggleButton btn_EfetuarAlocacao;
    private javax.swing.JToggleButton btn_RejeitarAlocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Alocacoes;
    // End of variables declaration//GEN-END:variables
}
