package apresentacao;

import java.awt.Toolkit;
import javax.swing.JFrame;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thiago
 */
public class MenuRelatorios extends javax.swing.JFrame {

    private JFrame previousFrame;
    
    public void addRadioButtons() {
        btnGroup_Tipo.add(rbtn_AlocacoesPendentes);
        btnGroup_Tipo.add(rbtn_AlocacoesPorDia);
        btnGroup_Tipo.add(rbtn_QuantidadedeSubstuicoesPorProfessor);
        btnGroup_Tipo.add(rbtn_SubstituicoesDetalhadasPorProfessor);
    }
    
    /**
     * Creates new form MenuRelatorios
     */
    public MenuRelatorios() {
        initComponents();
        this.setLocationRelativeTo(null);
        addRadioButtons();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Users/Thiago/Documents/NetBeansProjects/ProSub/mack_icon.jpg"));
    }

    public MenuRelatorios(JFrame previous) {
        initComponents();
        previousFrame = previous;
        this.setLocationRelativeTo(null);
        addRadioButtons();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Users/Thiago/Documents/NetBeansProjects/ProSub/mack_icon.jpg"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_Tipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbtn_AlocacoesPendentes = new javax.swing.JRadioButton();
        rbtn_SubstituicoesDetalhadasPorProfessor = new javax.swing.JRadioButton();
        rbtn_QuantidadedeSubstuicoesPorProfessor = new javax.swing.JRadioButton();
        rbtn_AlocacoesPorDia = new javax.swing.JRadioButton();
        btn_Cancelar = new javax.swing.JToggleButton();
        btn_Confirmar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emitir Relatórios");
        setName("frm_MenuRelatorios"); // NOI18N
        setResizable(false);

        jLabel1.setText("Escolha o tipo do relatório:");

        rbtn_AlocacoesPendentes.setSelected(true);
        rbtn_AlocacoesPendentes.setText("Alocações Pendentes");

        rbtn_SubstituicoesDetalhadasPorProfessor.setText("Substituições detalhadas realizadas por Professor");

        rbtn_QuantidadedeSubstuicoesPorProfessor.setText("Quantidade de substituições por professor");

        rbtn_AlocacoesPorDia.setText("Alocações por dia");

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Confirmar.setText("Confirmar");
        btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Confirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtn_SubstituicoesDetalhadasPorProfessor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_AlocacoesPendentes, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_QuantidadedeSubstuicoesPorProfessor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_AlocacoesPorDia, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_AlocacoesPendentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_SubstituicoesDetalhadasPorProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_QuantidadedeSubstuicoesPorProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_AlocacoesPorDia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Confirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ConfirmarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        try {
            this.dispose();
            previousFrame.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro ao retornar para janela anterior!");
        } 
    }//GEN-LAST:event_btn_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRelatorios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup_Tipo;
    private javax.swing.JToggleButton btn_Cancelar;
    private javax.swing.JToggleButton btn_Confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbtn_AlocacoesPendentes;
    private javax.swing.JRadioButton rbtn_AlocacoesPorDia;
    private javax.swing.JRadioButton rbtn_QuantidadedeSubstuicoesPorProfessor;
    private javax.swing.JRadioButton rbtn_SubstituicoesDetalhadasPorProfessor;
    // End of variables declaration//GEN-END:variables
}
