package apresentacao;

import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.ProfessorModel;
import servico.ListaProfessoresService;
import servico.NotificacaoService;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thiago Lima
 */
public class NotificarAusencia extends javax.swing.JFrame {
    
    private JFrame previousFrame;
    
    /**
     * Creates new form NotificarAusencia
     */
    public NotificarAusencia() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Users/Thiago/Documents/NetBeansProjects/ProSub/mack_icon.jpg"));             
        
        this.populateComboProfessor();
        
        
        
    }
    public NotificarAusencia(JFrame previous) {
        initComponents();
        previousFrame = previous;
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Users/Thiago/Documents/NetBeansProjects/ProSub/mack_icon.jpg"));
        
        this.populateComboProfessor();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_Professor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_DataInicio = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmb_DataFim = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_Motivo = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        cmb_ProfessorSugerido = new javax.swing.JComboBox();
        btn_Cancelar = new javax.swing.JToggleButton();
        confirmarButton = new javax.swing.JButton();
        txt_dataInicio = new javax.swing.JFormattedTextField();
        txt_dataFim = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Notificar Ausência");
        setName("frm_NotificarAusencia"); // NOI18N
        setResizable(false);

        jLabel1.setText("Professor:");

        jLabel2.setText("Data Início:");

        cmb_Professor.setToolTipText("Escolha o professor que se ausentará.");
        cmb_Professor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ProfessorItemStateChanged(evt);
            }
        });

        jLabel3.setText("Data Fim:");

        jLabel4.setText("Aula Início:");

        cmb_DataInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Aula 1", "Aula 2", "Aula 3", "Aula 4" }));
        cmb_DataInicio.setToolTipText("Escolha a primeira aula da ausência.");

        jLabel5.setText("Aula Fim:");

        cmb_DataFim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Aula 1", "Aula 2", "Aula 3", "Aula 4" }));
        cmb_DataFim.setToolTipText("Escolha a última aula da ausência");
        cmb_DataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_DataFimActionPerformed(evt);
            }
        });

        jLabel6.setText("Motivo:");

        txta_Motivo.setColumns(20);
        txta_Motivo.setRows(5);
        txta_Motivo.setToolTipText("Descreva o motivo da ausência.");
        jScrollPane1.setViewportView(txta_Motivo);

        jLabel7.setText("Professor Sugerido:");

        cmb_ProfessorSugerido.setToolTipText("Sugira um professor para ser o substituto nesta ausência.");
        cmb_ProfessorSugerido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ProfessorSugeridoItemStateChanged(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        txt_dataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyy"))));

        txt_dataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmb_Professor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_dataInicio)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_dataFim))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Cancelar)
                        .addGap(38, 38, 38)
                        .addComponent(confirmarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_ProfessorSugerido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_ProfessorSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar)
                    .addComponent(confirmarButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
         try {
            this.dispose();
            previousFrame.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro ao retornar para janela anterior!");
        }   
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void cmb_DataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_DataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_DataFimActionPerformed

    private void cmb_ProfessorSugeridoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ProfessorSugeridoItemStateChanged

    }//GEN-LAST:event_cmb_ProfessorSugeridoItemStateChanged

    private void cmb_ProfessorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ProfessorItemStateChanged
        if( evt.getStateChange() == ItemEvent.SELECTED && (cmb_Professor.getSelectedIndex() != 0)){
            
            cmb_ProfessorSugerido.removeAllItems();

            String nomeProfEscolhido = (String)evt.getItem();
            
            ListaProfessoresService profService = new ListaProfessoresService();
             
            List<ProfessorModel> professores = profService.ListarProfessores();
            
            for (ProfessorModel professor : professores){
                
                if(!professor.Nome.equals(nomeProfEscolhido)){
                    
                    cmb_ProfessorSugerido.addItem(professor.Nome);
                
                }

            }
        }
    }//GEN-LAST:event_cmb_ProfessorItemStateChanged

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        String nomeProfAusente = (String)cmb_Professor.getSelectedItem();
        String nomeProfSugerido = (String)cmb_ProfessorSugerido.getSelectedItem();

        ListaProfessoresService listProfService = new ListaProfessoresService();
        
        ProfessorModel profAusente = listProfService.obterProfessor(nomeProfAusente);
        ProfessorModel profSugerido = listProfService.obterProfessor(nomeProfSugerido);
        
        String dataInicio = txt_dataInicio.getText();
        String dataFim = txt_dataFim.getText();
        
        String motivo = txta_Motivo.getText();
        
        String codigoAusencia = null;
                
        NotificacaoService notService = new NotificacaoService();
        try {
            codigoAusencia = notService.notificarAusencia(profAusente.id, dataInicio, dataFim, motivo, profSugerido.id);
        } catch (ParseException ex) {
            Logger.getLogger(NotificarAusencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Ausência de nº " + codigoAusencia + " foi gerada.", "Notificação de Ausencia", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void populateComboProfessor(){
        cmb_Professor.addItem("- Selecione um professor - ");
        
        ListaProfessoresService profService = new ListaProfessoresService();          
        List<ProfessorModel> professores = profService.ListarProfessores();

        for(ProfessorModel professor : professores){
            
            cmb_Professor.addItem(professor.Nome);
            
        } 
    }
            
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificarAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificarAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificarAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificarAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotificarAusencia().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_Cancelar;
    private javax.swing.JComboBox cmb_DataFim;
    private javax.swing.JComboBox cmb_DataInicio;
    private javax.swing.JComboBox cmb_Professor;
    private javax.swing.JComboBox cmb_ProfessorSugerido;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txt_dataFim;
    private javax.swing.JFormattedTextField txt_dataInicio;
    private javax.swing.JTextArea txta_Motivo;
    // End of variables declaration//GEN-END:variables
}
