package apresentacao;

import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ProfessorModel;
import org.joda.time.DateTime;
import org.joda.time.Interval;
import servico.ProfessorService;
import servico.NotificacaoService;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thiago Lima
 */
public class NotificacaoDeAusencia extends javax.swing.JFrame {
    
    private JFrame previousFrame;
    
    /**
     * Creates new form NotificarAusencia
     */
    public NotificacaoDeAusencia() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Users/Thiago/Documents/NetBeansProjects/ProSub/mack_icon.jpg"));             
        
        this.populateComboProfessor();
        
        
        
    }
    public NotificacaoDeAusencia(JFrame previous) {
        initComponents();
        previousFrame = previous;
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:/Users/Thiago/Documents/NetBeansProjects/ProSub/mack_icon.jpg"));
        
        this.populateComboProfessor();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_Professor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_Motivo = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        cmb_ProfessorSugerido = new javax.swing.JComboBox();
        btn_Voltar = new javax.swing.JToggleButton();
        confirmarButton = new javax.swing.JButton();
        txt_dataInicio = new javax.swing.JFormattedTextField();
        txt_dataFim = new javax.swing.JFormattedTextField();
        adicionarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaIndicacoes = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Notificar Ausência");
        setName("frm_NotificarAusencia"); // NOI18N
        setResizable(false);

        jLabel1.setText("Professor:");

        jLabel2.setText("Data Início:");

        cmb_Professor.setToolTipText("Escolha o professor que se ausentará.");
        cmb_Professor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ProfessorItemStateChanged(evt);
            }
        });

        jLabel3.setText("Data Fim:");

        jLabel6.setText("Motivo:");

        txta_Motivo.setColumns(20);
        txta_Motivo.setRows(5);
        txta_Motivo.setToolTipText("Descreva o motivo da ausência.");
        jScrollPane1.setViewportView(txta_Motivo);

        jLabel7.setText("Professores que poderão ver a notificação de ausência:");

        cmb_ProfessorSugerido.setToolTipText("Sugira um professor para ser o substituto nesta ausência.");
        cmb_ProfessorSugerido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ProfessorSugeridoItemStateChanged(evt);
            }
        });

        btn_Voltar.setText("Voltar");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        txt_dataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyy"))));

        txt_dataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        adicionarButton.setText("Adicionar");
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });

        tabelaIndicacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Professor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaIndicacoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_ProfessorSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(adicionarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Voltar)
                        .addGap(26, 26, 26)
                        .addComponent(confirmarButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_ProfessorSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Voltar)
                    .addComponent(confirmarButton))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
         try {
            this.dispose();
            previousFrame.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro ao retornar para janela anterior!");
        }   
    }//GEN-LAST:event_btn_VoltarActionPerformed

    private void cmb_ProfessorSugeridoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ProfessorSugeridoItemStateChanged

    }//GEN-LAST:event_cmb_ProfessorSugeridoItemStateChanged

    private void cmb_ProfessorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ProfessorItemStateChanged
        if( evt.getStateChange() == ItemEvent.SELECTED && (cmb_Professor.getSelectedIndex() != 0) &&
                !txt_dataInicio.getText().equals("") && !txt_dataFim.getText().equals("") ){
            
            cmb_ProfessorSugerido.removeAllItems();

            String nomeProfEscolhido = (String)evt.getItem();
            
            ProfessorService profService = new ProfessorService();
             
            //List<ProfessorModel> professores = profService.ListarProfessores();
            
            String dataInicio = txt_dataInicio.getText();
            String dataFim = txt_dataFim.getText();
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        
            DateTime inicio = null;
            DateTime fim = null;
            try {
                inicio = new DateTime(sdf.parse(dataInicio));
                fim = new DateTime(sdf.parse(dataFim));
            } catch (ParseException ex) {
                Logger.getLogger(NotificacaoDeAusencia.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Interval periodo = new Interval(inicio, fim);
            
            List<ProfessorModel> professores = profService.ListarProfessores();
            
            cmb_ProfessorSugerido.addItem("- Indique professores - ");
            
            for (ProfessorModel professor : professores){
                
                if(!professor.Nome.equals(nomeProfEscolhido)){
                    
                    cmb_ProfessorSugerido.addItem(professor.Nome);
                
                }

            }
        }
    }//GEN-LAST:event_cmb_ProfessorItemStateChanged

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        String nomeProfAusente = (String)cmb_Professor.getSelectedItem();
        //String nomeProfSugerido = (String)cmb_ProfessorSugerido.getSelectedItem();

        ProfessorService listProfService = new ProfessorService();
        
        ProfessorModel profAusente = listProfService.obterProfessorPorNome(nomeProfAusente);
        //ProfessorModel profSugerido = listProfService.obterProfessor(nomeProfSugerido);
        
        String dataInicio = txt_dataInicio.getText();
        String dataFim = txt_dataFim.getText();
        
        String motivo = txta_Motivo.getText();
        
        String codigoAusencia = null;
                
        NotificacaoService notService = new NotificacaoService();
        
        DefaultTableModel tableModel = (DefaultTableModel) tabelaIndicacoes.getModel();
        
        int linhas = tableModel.getRowCount();
        int colunas = 1;
        
        List<String> nomeProfs = new ArrayList<String>();
        
        for(int i = 0 ; i < linhas ; i++){
            nomeProfs.add((String)tableModel.getValueAt(i, 0));
        }
        
        try {
            codigoAusencia = notService.notificarAusencia(profAusente.id, dataInicio, dataFim, motivo, nomeProfs);
        } catch (ParseException ex) {
            Logger.getLogger(NotificacaoDeAusencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Ausência de nº " + codigoAusencia + " foi gerada.", "Notificação de Ausencia", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
        
        if(cmb_ProfessorSugerido.getSelectedIndex() != 0 ){
            
            String nomeProf = (String) cmb_ProfessorSugerido.getSelectedItem();
            
            DefaultTableModel tableModel = (DefaultTableModel) tabelaIndicacoes.getModel();
            
            tableModel.addRow(new Object[]{nomeProf});
            
            cmb_ProfessorSugerido.removeItemAt(cmb_ProfessorSugerido.getSelectedIndex());
        }
        
    }//GEN-LAST:event_adicionarButtonActionPerformed

    private void populateComboProfessor(){
        cmb_Professor.addItem("- Selecione um professor - ");
        
        ProfessorService profService = new ProfessorService();          
        List<ProfessorModel> professores = profService.ListarProfessores();

        for(ProfessorModel professor : professores){
            
            cmb_Professor.addItem(professor.Nome);
            
        } 
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificacaoDeAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificacaoDeAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificacaoDeAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificacaoDeAusencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotificacaoDeAusencia().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JToggleButton btn_Voltar;
    private javax.swing.JComboBox cmb_Professor;
    private javax.swing.JComboBox cmb_ProfessorSugerido;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaIndicacoes;
    private javax.swing.JFormattedTextField txt_dataFim;
    private javax.swing.JFormattedTextField txt_dataInicio;
    private javax.swing.JTextArea txta_Motivo;
    // End of variables declaration//GEN-END:variables
}
